# Generated by Django 2.2.9 on 2020-01-28 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'events'},
        ),
        migrations.AddField(
            model_name='event',
            name='userid',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
    ]
